server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka}

zuul:
  ignoredServices: '*'
  routes:
    apiB:
      path: /hello/**
      serviceId: api-b
      #url: http://localhost:57722/
management:
  endpoints:
    web:
      exposure:
        include: routes,filters,health,env,metrics,trace,info,refresh,loggers

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
